# Generated by Django 4.2 on 2023-04-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="connectedemail",
            old_name="email",
            new_name="email_address",
        ),
        migrations.RemoveField(
            model_name="connectedemail",
            name="password",
        ),
        migrations.RemoveField(
            model_name="connectedemail",
            name="provider",
        ),
        migrations.AddField(
            model_name="connectedemail",
            name="access_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="connectedemail",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connectedemail",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
