# Generated by Django 4.2 on 2023-04-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_email_connectedemail_email_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectedemail",
            name="provider",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
