# Generated by Django 4.2 on 2023-04-16 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_rename_email_connectedemail_email_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=50)),
                ("email_address", models.EmailField(max_length=254)),
                ("company", models.CharField(max_length=255)),
                ("website", models.URLField()),
                (
                    "registered_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.user"
                    ),
                ),
            ],
        ),
    ]
