# Generated by Django 4.2 on 2023-04-16 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="registered_user",
        ),
    ]
